function [] = test_B_byPlotting()
%function [] = test_B_byPlotting()
% Written by: David DeVries
% evaluates B over multiple x and z values (takes plane in y) and plots the
% magnetic field

close all;

hFig1 = figure(1);

% generate grid coordinates to plot the field in the y plane
[x, z] = meshgrid(-0.05:0.01:0.05,-.05:.01:.1);
y = 0;

% calculate the number of rows and cols.
[numRows, numCols] = size(x); 

% initialize values for B components
Bx = zeros(size(x));
By = zeros(size(x));
Bz = zeros(size(x));

% since B is not vectorize, we must loop through each point
for r=1:numRows
    for c=1:numCols
        [Bx(r,c),By(r,c),Bz(r,c)] = B(x(r,c), y, z(r,c));
    end
end

% plot the field
quiver(x,z,Bx,Bz, 'Color', 'k', 'LineWidth', 1.1);
xlabel('x-axis');
ylabel('z-axis');
axis equal;

set( gcf, 'Units', 'Inches', 'Position', [0 0 8.5 8.5] )
set( gca                                    ,...
    'FontName'     ,   'Helvetica'             ,...
    'FontSize'     ,   16                  ,...
    'Box'          ,   'off'                ,...
    'XAxisLocation',   'bottom'            ,...
    'YAxisLocation',   'left'              ,...
    'TickDir'      ,   'in'                ,...
    'TickLength'   ,   [0.03 0.03]         ,...
    'XMinorTick'   ,   'off'                ,...
    'YMinorTick'   ,   'off'                ,...
    'XColor'       ,   'black'             ,...
    'YColor'       ,   'black'             ,...
    'XLim'         ,   [-0.06, 0.06]   ,...
    'YLim'         ,   [-0.06, 0.11]   ,...
    'XTick'        ,   [-0.05, -0.025, 0, 0.025, 0.05],...
    'YTick'        ,   [-0.05, -0.025, 0, 0.025, 0.05, 0.075, 0.1],...
    'Color'        ,   'white'             ,...
    'LineWidth'    ,   1.1                   ,...
    'Units'        ,   'Inches'            ,...
    'PlotBoxAspectRatio', [1, 1, 1]       );

%saveas(hFig1, 'testBbyPlottingOutput.png')

end

